var redPieces = {
  'compKing': 'e8',
  'compQueen': 'd8',
  'compBishop1': 'f8',
  'compBishop2': 'c8',
  'compRook1': 'a8',
  'compRook2': 'h8',
  'compKnight1': 'b8',
  'compKnight2': 'g8',
  'compPawn1': 'a7',
  'compPawn2': 'b7',
  'compPawn3': 'c7',
  'compPawn4': 'd7',
  'compPawn5': 'e7',
  'compPawn6': 'f7',
  'compPawn7': 'g7',
  'compPawn8': 'h7',
  'enemyInRange': [],
  'totalPieces': ['compKing','compQueen', 'compBishop1', 'compBishop2','compRook1','compRook2','compKnight1','compKnight2','compPawn1','compPawn2','compPawn3','compPawn4','compPawn5','compPawn6','compPawn7','compPawn8'],
  'inCheck': 'no',
  'stillInCheck': [],
  'count': 0
}